spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security-homework?currentSchema=account
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 5
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresFinal
    database-platform: org.hibernate.dialect.PostgreSQLDialect