INSERT INTO Users (user_name, password, name, phone_number)
VALUES ('admin','admin','admin','8000000'),
('user','user','user','7000000');

INSERT INTO Roles (role_name, description)
VALUES ('ROLE_ADMIN', 'ADMIN'),
('ROLE_USER', 'USER');

INSERT INTO UsersRoles (user_id, role_id)
VALUES (1, 1),
(2, 2);

INSERT INTO Products (name, description, user_id, price, currency)
VALUES ('adminProduct','adminProduct',1, 10.02, 'RUB');

CREATE TABLE IF NOT EXISTS Products(
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500) NOT NULL,
    user_id BIGINT NOT NULL,
    price DECIMAL(10,2),
    currency VARCHAR(255)
);