INSERT INTO Users (user_name, password, name, phone_number)
VALUES ('admin','admin','admin','8000000'),
('user','user','user','7000000');

INSERT INTO Roles (role_name, description)
VALUES ('ROLE_ADMIN', 'ADMIN'),
('ROLE_USER', 'USER');

INSERT INTO UsersRoles (user_id, role_id)
VALUES (1, 1),
(2, 2);

INSERT INTO Products (product_name, description, user_id, price, currency)
VALUES ('adminProduct','adminProduct',1, 10.02, 'RUB');

INSERT INTO Deals (seller_id, buyer_id, product_id, deal_date, deal_price, currency)
VALUES (1,2,1, '2024-01-01 00:00:00', 1110.02, 'RUB');

CREATE TABLE IF NOT EXISTS Deals(
    deal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT,
    buyer_id BIGINT,
    product_id BIGINT,
    deal_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    deal_price DECIMAL(10,2),
    currency VARCHAR(255)
);