
CREATE TABLE IF NOT EXISTS Users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255) NOT NULL,
    role varchar(100) not null
);

CREATE TABLE IF NOT EXISTS Products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    description VARCHAR(500) NOT NULL,
    user_id BIGINT NOT NULL,
    price DECIMAL(10,2),
    currency VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Deals(
    deal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT,
    buyer_id BIGINT,
    product_id BIGINT,
    deal_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    deal_price DECIMAL(10,2),
    currency VARCHAR(255)
);
